### ISSUE TITLE
Ads not blocked

### ISSUE THREAD

**Issue by frontalot** [teffalump/adblock#4]
I downloaded and installed your script per the readme instructions. Everything appears to run fine (minus one "uci: Entry not found" line), but no ads are actually blocked. I checked /etc/config/dhcp and the block.hosts line is there so I don't know what's wrong.

Any ideas on how to troubleshoot? I'm running a persistent OpenVPN connection and all traffic is routed through said connection, if that makes any difference.

**Comment by frontalot** [comment]
Here is my /etc/config/dhcp setup:

config dnsmasq
        option boguspriv '1'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/lan/'
        option expandhosts '1'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.auto'
        option localservice '1'
        option domain 'HOME'
        option domainneeded '1'
        option strictorder '1'
        option filterwin2k '1'
        option noresolv '0'
        list addnhosts '/etc/block.hosts'

config dhcp 'lan'
        option interface 'lan'
        option leasetime '12h'
        option start '102'
        option limit '199'
        list dhcp_option '6,209.222.18.222,209.222.18.218,8.8.8.8,8.8.4.4,74.82.42.42'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'

config dhcp 'guest'
        option leasetime '12h'
        option interface 'guest'
        option start '102'
        option limit '199'
        list dhcp_option '6,209.222.18.222,209.222.18.218,8.8.8.8,8.8.4.4,74.82.42.42'

**Comment by teffalump** [comment]
Yes, the issue is that localservice is '1' --- basically, the router will not answer DNS requests from subnets **not** attached to an interface (e.g., the VPN). To fix that, you can set localservice to '0'. However, there are some precautions to take. That setting is one way to prevents DNS reflection attacks, consequently, make sure the router is not answering external DNS requests, etc. We had a little discussion on the gist thread about this. Also, I just pushed a commit that provides a hint about just this scenario. Thanks! =-)

**Comment by frontalot** [comment]
Thanks for the quick response. I'll continue this discussion over on the gist.
